config/routes.rb
Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Upmin::Engine => '/admin'
  end
  devise_for :users
  root 'static_pages#home'
  resources :time_slots, only: :create
  resources :schedules, only: [:create, :show] do
    member { post 'generate' }
  end

end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :lectures
end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
	belongs_to :course
	belongs_to :meeting
	belongs_to :schedule
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
	validates :schedule_id, uniqueness: { scope: :time_slot_id }
  belongs_to :schedule
  belongs_to :time_slot
  has_one :lecture
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :user
  has_many :meetings
  has_many :time_slots, through: :meetings
  has_many :lectures



  def generate
    @time_count = time_slots.count
  	array = Array.new(lecture_days.size){Array.new(periods_per_day, 0)}
  	lectures_by_priority = lectures.sort{|x,y| y.periods <=> x.periods}
    return false unless check_valid_list? (lectures_by_priority)
   	table = recursive_insert(array, lectures_by_priority, choice = 0)
   	update(result: (table.map {|row| row.map{ |ele| ele.try(:id)}}))
  end

  def check_valid_list?(lecture_list)
    check_no_overlapping_courses(lecture_list) && check_total_period_within_time(lecture_list)
  end

  def check_total_period_within_time(lecture_list)
    (lecture_days.size * periods_per_day)/lecture_list.map(&:periods).inject{ |sum, x| sum + x }
  end

  def check_no_overlapping_courses(lecture_list)
    frequency = score(lecture_list.map { |x| x.course.id })
    if frequency.max_by{|k,v| v}[1] > lecture_days.size
      return false
    else
      return true
    end
  end

  def score( array )
    array.each_with_object(Hash.new(0)){|key,hash| hash[key] += 1}
  end

  # def recursive_insert(array, lecture_list, choice = 0)
  # 	current_array = Marshal.load(Marshal.dump(array))


		# if lecture_list == []
		# 	return array


		# elsif choice > time_slots.count
  #     return "try next"


		# elsif updated_array = insert_lecture(current_array, lecture_list[0], choice)
		# 	updated_array = recursive_insert(updated_array, lecture_list[1..-1])
		

  #   else
  #     p "failed"
		# 	recursive_insert(current_array, lecture_list, choice + 1)
		# end
		# updated_array
  # end
  def recursive_insert(array, lecture_list, choice = 0)
    current_array = Marshal.load(Marshal.dump(array))
    p "#{array.map {|row| row.map{ |ele| ele.try(:id)}}}"
    if lecture_list == []
      return array
    end

    result = false
    while choice < @time_count && result == false
      new_array = Marshal.load(Marshal.dump(array))
      if updated_array = insert_lecture(new_array, lecture_list[0], choice)
        p "Scope #{lecture_list[0]}"
       result = recursive_insert(updated_array, lecture_list[1..-1], 0)
      end
      choice += 1
    end
    result
  end

  # def recursive_insert(array, lecture_list, choice = 0)
  #   current_array = Marshal.load(Marshal.dump(array))
  #   p "scope #{lecture_list[0].id}"
  #   #try to put in first_element

  #   if lecture_list == []
  #     return current_array
  #   elsif updated_array = insert_lecture(current_array, lecture_list[0], choice)
  #     p 'inserted'
  #     if recursive_insert(updated_array, lecture_list[1..-1], 0)
  #       return array
  #     else
  #       return recursive_insert(current_array, lecture_list, 1)
  #     end
  #   else
  #     result = false
  #     until choice > time_slots.count || result
  #       p "itereating through it #{choice}"
  #       result = recursive_insert(array, lecture_list, choice += 1)
  #       choice += 1
  #     end
  #     if choice > time_slots.count 
  #       return false
  #     else
  #       return result
  #     end
  #   end

  # end



  def insert_lecture(array, lecture, choice)
  	count = 0
  	lecture_length = lecture.periods
  	array.each do |row|
  		if lecture_course_same_day(row, lecture)
  			next
  		else
  			#check whether lecture fits
  			row.each_with_index do |ele, index|
  				if ele == 0 && row.length >= lecture_length + index
  					if count == choice
	  					lecture_length.times do |x|
		  					row[index+x] = lecture
		  				end
		  				return array
		  			else
		  				count += 1
		  			end
  				end
  			end
  		end
  	end
  	return false
  end

  def lecture_course_same_day(row, lecture)
  	row.each do |ele|
  		if ele.kind_of? Lecture
  			return true if lecture.course == ele.course
  		end
  	end
  	return false
  end

  def lecture_days
  	time_slots.pluck(:day).uniq
  end

  def periods_per_day
  	time_slots.count/lecture_days.size
  end
end

app/models/time_slot.rb
class TimeSlot < ActiveRecord::Base
	has_many :meetings
  has_many :schedules, through: :meetings


	def self.create_time_slots(schedule, options = {period: 60, start_time: 0, end_time: 1440,
																 start_day: 0, end_day: 7})
	  end_time = options[:end_time].to_i
	  start_time = options[:start_time].to_i
	  period = options[:period].to_i
	  start_day = options[:start_day].to_i
	  end_day = options[:end_day].to_i

		periods_per_day = (end_time - start_time)/period
		number_of_days = (end_day - start_day) + 1
		number_of_days.times do |day|
			periods_per_day.times do |num|
				time_slot = TimeSlot.find_or_create_by day: start_day + day,
												start_time: start_time + (num*period),
												end_time: start_time + ((num + 1)*period)
				schedule.time_slots << time_slot
			end
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :schedules
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def create
  	@schedule = current_user.schedules.build(schedule_params)
  	@schedule.save
  	@user_schedules = current_user.schedules(true)
  	render 'static_pages/home'
  end

  def show
    @schedule = Schedule.find(params[:id])
    @start_time = @schedule.time_slots.pluck(:start_time).min
    @time = @start_time
    @end_time = @schedule.time_slots.pluck(:start_time).max
    one_time_slot = @schedule.time_slots.first
    @period = one_time_slot.end_time - one_time_slot.start_time
    @days = @schedule.time_slots.pluck(:day).uniq
    @result = @schedule.result
  end

  def generate
    @schedule = Schedule.find(params[:id])
    flash[:danger] = "Invalid Lecture List" unless @schedule.generate
    redirect_to schedule_path(@schedule)
  end

  private

  def schedule_params
  	params.require(:schedule).permit(:name)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@schedule = current_user.schedules.build
  	@user_schedules = current_user.schedules(true)
  end
end

app/controllers/time_slots_controller.rb
class TimeSlotsController < ApplicationController
  def create
  	@schedule = Schedule.find(params[:schedules][:schedule_id])
  	TimeSlot.create_time_slots(@schedule, time_slots_params)
  	redirect_to root_url
  end

  private

  def time_slots_params
  	params.require(:time_slots).permit(:period, :start_time, :end_time,
  	 :start_day, :end_day)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetable</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>
  <%= link_to "Login", new_user_session_path %>
  <%= link_to "Sign Up", new_user_registration_path %>
	<%= yield %>

</body>
</html>

app/views/schedules/show.html.erb
<table class="table">
	<thead>
		<tr>
			<th></th>
			<% while @time <= @end_time do %>
				<th><%= "#{@time/60}:#{'%02d' % (@time%60)} - #{(@time+@period)/60}:#{'%02d' % ((@time+@period)%60)}" %></th>
				<% @time += @period %>
			<% end %>
		</tr>
	</thead>
	<tbody>
		<% @days.each_with_index do |day, index| %>
			<tr>
				<td>
					<%= Date::DAYNAMES[day] %>
				</td>
				<% @result[index].each do |ele| %>
					<td><%= Lecture.find_by(id: ele).try(:name) unless ele == nil %></td>
				<% end %>
			</tr>
		<% end %>
	</tbody>
</table>

<%= link_to button_tag("Generate!"), generate_schedule_path, method: :post %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(object.errors.count, "error") %>
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li>
					<%= msg %>
				</li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/home.html.erb
<h1> Home </h1>

<h3>Create Schedule</h3>
<%= form_for @schedule do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<%= f.label "name" %>
	<%= f.text_field :name %>

	<%= f.submit %>
<% end %>

<h3>Create Time Periods</h3>

<%= form_for :time_slots, {url: time_slots_path } do |f| %>
	
	<%= collection_select(:schedules, :schedule_id, @user_schedules, :id, :name) %>

	<%= label_tag "Set lowest common period" %>
	<%= f.number_field :period, {value: 60, within: (15..120)} %>

	<%= label_tag "Start Time(minutes from midnight)" %>
	<%= f.number_field :start_time, {value: 480, within: (0..1440)} %>

	<%= label_tag "End Time(minutes from midnight)" %>
	<%= f.number_field :end_time, {value: 1080, within: (0..1440)} %>


	<% days_to_value = Date::DAYNAMES.each_with_index.map{|x,i| [x,i]} %>

	<%= label_tag "Start day" %>
	<%= f.select :start_day, days_to_value, {selected: 1}  %>

	<%= label_tag "End day" %>
	<%= f.select :end_day, days_to_value, {selected: 5 } %>

	<%= submit_tag "Create Periods" %>
<% end%>

app/views/upmin/partials/models/_new_model.html.haml
.upmin-model{class: model.color}
  %h3
    Create a
    = model.humanized_name(:singular)

  %br
  %br
  %h3{style: "color: #333;"}
    Attributes
  %hr

  .attributes
    -# Yes this is meant to be model.model - this is the raw rails model instance.
    = form_for(model, url: model.create_path, html: { method: :post }) do |f|

      -# Render each attribute
      - model.attributes.each do |attribute|
        = up_render(attribute, locals: { form_builder: f })

      = f.submit("Create", class: "btn btn-primary")

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>